#!/usr/bin/env python3
"""Build B3.1 Gas Exchange cloze deck (50 cards) for the Bio HL deck.
Matches the user's existing 'Cloze+' note model (Text + Back Extra) so cards
merge cleanly into Anki and anki-arena can read them.
Usage: python build_b31_anki.py  ->  writes B3.1_Gas_Exchange.apkg
"""
import genanki, os

MODEL_ID = 1613201144
DECK_ID  = 2059400110  # same Bio HL deck as C2.1 -> merges
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "topics", "bio", "gas-exchange", "B3.1_Gas_Exchange.apkg")

model = genanki.Model(
    MODEL_ID,
    "Cloze+",
    fields=[{"name": "Text"}, {"name": "Back Extra"}],
    templates=[{
        "name": "Cloze",
        "qfmt": "{{cloze:Text}}",
        "afmt": '{{cloze:Text}}<br><div style="color:#a855f7;font-style:italic">{{Back Extra}}</div>',
    }],
    model_type=1,  # cloze
)

CARDS = [
# --- B3.1.1 gas exchange vital in all organisms ---
("Every organism carries out gas exchange: in aerobic {{c1::respiration}} O₂ is taken in and {{c2::CO₂}} is released as waste. In {{c3::photosynthesis}} (plants), {{c4::CO₂}} is taken in and O₂ is released.",
 "The universal two-for-one deal. 🎟 Every living venue runs it. (b3.1.1)"),
("Diffusion is the physical basis of gas exchange — molecules move from regions of {{c1::high concentration}} to {{c2::low concentration}}. It only works over {{c3::short distances}}.",
 "Gases are lazy: they roll downhill. ⛰ (b3.1.1)"),
("As organisms get bigger, the surface-area-to-volume ratio {{c1::decreases}} and the distance from the centre of the organism to the exterior {{c2::increases}} — so large organisms need a specialised exchange surface such as {{c3::alveoli}}, {{c3::gills}} or {{c3::spongy mesophyll}}.",
 "Small club = everyone's at the window; megaclub = the centre can't breathe. 🐋 (b3.1.1)"),
("A flatworm can exchange gases directly over its body surface because it has a {{c1::large surface area to volume ratio}} and a {{c2::short distance}} from centre to exterior.",
 "The tiny club with no doors needed. 🪱 (b3.1.1)"),
("The animal with blood and water separated by only ~10 µm of tissue, keeping feathery external gills as an adult, is the {{c1::axolotl}}.",
 "Bonus animal facts. 🦎 (b3.1.1)"),
("Spheres have the {{c1::smallest}} surface-area-to-volume ratio of any shape — which is why exchange surfaces are built from enormous numbers of tiny {{c2::spherical}} units (alveoli).",
 "Tiny spheres = huge total area. 📏 (b3.1.1)"),
# --- B3.1.2 properties of gas-exchange surfaces ---
("The four properties of gas-exchange surfaces: {{c1::large surface area}} relative to volume, {{c2::thin}} tissue layer, {{c3::moist}} surface, and {{c4::permeable}} to gases.",
 "THE DOOR RULES: large · thin · moist · permeable. 🚪 (b3.1.2)"),
("Gases diffuse across membranes faster when they are {{c1::dissolved in a film of moisture}}.",
 "Wet floor rule. 💧 (b3.1.2)"),
("SMART is a mnemonic for exchange surfaces: {{c1::Surface}} area, {{c2::Moisture}}, {{c3::Absorptive}}/permeable, {{c4::Rich}} blood network, {{c5::Thin}}.",
 "SMART door sign. 🪩 (b3.1.2)"),
("A single alveolus wall is about {{c1::0.2 µm}} thick — one layer of cells — so gases diffuse only a very {{c2::short distance}}.",
 "One-cell-deep velvet rope. 🧵 (b3.1.2)"),
# --- B3.1.3 maintaining concentration gradients in animals ---
("Three ways animals maintain the concentration gradient at an exchange surface: {{c1::dense capillary networks}}, {{c2::continuous blood flow}} (blood arrives low in O₂, high in CO₂), and {{c3::ventilation}} of air or water.",
 "Gradient law: keep the inside poor and the outside fresh. ⛰ (b3.1.3)"),
("In a tiny organism with no transport system, the gradient is maintained by the cells' own {{c1::respiration}}, which keeps internal O₂ low and CO₂ high.",
 "The crowd itself keeps the air fresh. 🪱 (b3.1.3)"),
("Partial pressure of O₂ (mmHg) on the journey in: atmospheric {{c1::159}} → alveolar {{c2::105}} → blood arriving {{c3::40}} → exhaled {{c4::120}}. CO₂ runs the staircase backwards.",
 "The gradient staircase. 📊 (b3.1.3)"),
("Alveolar air has LOWER O₂ than fresh air because it {{c1::mixes with stale air}} left in the lungs and {{c2::O₂ constantly diffuses into the blood}}.",
 "DBQ trap — give BOTH reasons. 📊 (b3.1.3)"),
("Nitrogen barely diffuses at the exchange surface because the blood is already {{c1::saturated}} with it — there is no gradient.",
 "N₂ stays put. 📊 (b3.1.3)"),
("In fish gills, water and blood flow in {{c1::opposite directions}} ({{c2::countercurrent}} exchange), so a concentration gradient is maintained along the whole gill.",
 "The one-way queue. 🐟 (b3.1.3)"),
("Ventilation rate in mammals is tuned to the {{c1::CO₂ concentration of the blood}} — more CO₂, faster breathing.",
 "The bouncer watches the smoke level. 🫁 (b3.1.3)"),
# --- B3.1.4 adaptations of mammalian lungs ---
("The airflow route in a mammal: trachea → {{c1::bronchi}} → {{c2::bronchioles}} → {{c3::alveoli}}.",
 "Entrance corridor → staircases → hallways → VIP booths. 🏗 (b3.1.4)"),
("The trachea is lined with {{c1::cilia}} and {{c2::mucus}} to trap and expel foreign particles.",
 "The dust-trap VIP lane. 🏗 (b3.1.4)"),
("The trachea and bronchi are held open by {{c1::cartilage}}, while bronchioles can change width via {{c2::smooth muscle}} in their walls.",
 "Rigid ducting, adjustable corridors. 🏗 (b3.1.4)"),
("Four key adaptations of mammalian lungs: {{c1::surfactant}}, a {{c2::branched network of bronchioles}}, extensive {{c3::capillary beds}}, and a very {{c4::large surface area}}.",
 "THE FOUR EXAM ADAPTATIONS — memorise the list. 🎈 (b3.1.4)"),
("An adult pair of human lungs has about {{c1::300 million}} alveoli, giving a total surface area roughly {{c2::40 times}} the outside of the body (about a tennis court).",
 "The dance floor no one sees. 🎈 (b3.1.4)"),
("{{c1::Type I pneumocytes}} (AT1 cells) form the ultra-thin alveolar wall where gas exchange happens; {{c2::Type II pneumocytes}} (AT2 cells) secrete {{c3::surfactant}}.",
 "AT1 = the wall, AT2 = the spray. 🧪 (b3.1.4)"),
("Surfactant forms a {{c1::monolayer}} on the moisture film — hydrophilic heads in the {{c2::water}}, hydrophobic tails facing the {{c3::air}} — lowering {{c4::surface tension}} so the wet alveolar walls don't stick together and the lungs don't {{c5::collapse}} on exhalation.",
 "The anti-stick spray. 🎈 (b3.1.4)"),
("Elastic fibres in the lung tissue {{c1::stretch}} during inhalation and {{c2::recoil}} for passive exhalation; {{c3::collagen}} strengthens the tissue.",
 "The building springs back on its own. 🎈 (b3.1.4)"),
("In COPD (e.g. from smoking), airways become {{c1::narrower}} and the air sacs become {{c2::fewer and larger}} → less gas-exchange surface → patients feel tired because less {{c3::O₂ reaches the blood}}, so less aerobic respiration → less {{c4::ATP}}.",
 "The smoking DBQ. 📉 (b3.1.4)"),
# --- B3.1.5 ventilation ---
("Inspiration: the {{c1::diaphragm}} contracts and {{c2::flattens}}, and the {{c3::external intercostals}} contract pulling the ribs {{c4::up and out}} → thorax volume ↑ → pressure {{c5::drops below atmospheric}} → air is pulled in.",
 "DROP THE FLOOR, LIFT THE ROOF, SUCK THE AIR. 🌬 (b3.1.5)"),
("At rest, expiration is mostly {{c1::passive}}: muscles relax, the diaphragm returns to a {{c2::dome}} shape, and elastic fibres {{c3::recoil}} → volume ↓ → pressure {{c4::above atmospheric}} → air is forced out.",
 "LET GO. 🌬 (b3.1.5)"),
("Forced expiration uses the {{c1::internal intercostal}} muscles (pull ribs down and in) plus the {{c2::abdominal}} muscles (push organs and diaphragm upwards).",
 "LET GO, PLUS SQUEEZE. 🌬 (b3.1.5)"),
("Air is never pushed INTO the lungs — it flows because thoracic pressure falls {{c1::below atmospheric}} pressure during inspiration.",
 "You don't inhale; the room does. 🌬 (b3.1.5)"),
("The muscle that flattens during inspiration, increasing thoracic volume, is the {{c1::diaphragm}}; the pair of muscles that lift the ribs are the {{c2::external intercostals}}.",
 "Floor + roof team. 🌬 (b3.1.5)"),
# --- B3.1.6 lung volumes ---
("{{c1::Tidal volume}} = the volume of air in one normal breath in and out (~{{c2::500 mL}}).",
 "The regular sip. 🥤 (b3.1.6)"),
("{{c1::Inspiratory reserve volume}} = extra air you can force in AFTER a normal inhalation; {{c2::Expiratory reserve volume}} = extra air you can force out AFTER a normal exhalation.",
 "The reserves. 🥤 (b3.1.6)"),
("{{c1::Vital capacity}} = the maximum exhaled volume after a maximum inhalation = {{c2::IRV + tidal volume + ERV}}.",
 "THE FULL SWING — know the equation. 🥤 (b3.1.6)"),
("The air that can never be expelled, even after a maximum exhalation, is the {{c1::residual volume}} (~20% of total lung capacity).",
 "What never leaves the building. 🥤 (b3.1.6)"),
("A {{c1::spirometer}} measures the volume of air inhaled and exhaled (flow in/out), from which tidal volume and vital capacity are deduced.",
 "The fire marshal's meter. 📏 (b3.1.6)"),
("In a simple lung-volume measurement, a balloon is inflated with a single breath and its volume found by {{c1::submerging it in water}} and measuring the volume of water displaced (1 mL = 1 cm³).",
 "AOS — the balloon trick. 🎈 (b3.1.6)"),
("Adult resting ventilation rate is roughly {{c1::12–16 breaths per minute}}.",
 "The marshal counts breaths. ⏱ (b3.1.6)"),
# --- B3.1.7 leaf adaptations ---
("The leaf's outer surfaces are covered by a {{c1::waxy cuticle}} — a waterproof layer with {{c2::low}} gas permeability, thicker on the {{c3::upper}} surface and in {{c4::dry}} habitats.",
 "The roof sealant. 🌿 (b3.1.7)"),
("The tightly packed, chloroplast-rich cells in the upper part of a leaf are the {{c1::palisade mesophyll}}; the loosely packed cells with extensive air spaces are the {{c2::spongy mesophyll}}.",
 "Solar panels upstairs, airy lobby downstairs. 🌿 (b3.1.7)"),
("The exchange surface of a leaf is the permanently {{c1::moist}} walls of the cells around the {{c2::air spaces}} — CO₂ dissolves, diffuses to chloroplasts; O₂ diffuses out via {{c3::stomata}}.",
 "The wet walls do the deals. 🌿 (b3.1.7)"),
("Stomatal pores are flanked by two {{c1::guard cells}} that open and close the pore by changing shape.",
 "The bouncer windows. 🌿 (b3.1.7)"),
("A leaf's vascular bundles (veins) contain {{c1::xylem}} — transporting water and minerals up from the roots — and {{c2::phloem}} — transporting dissolved sugars out as sap.",
 "Water in the bar line, sugar to the till. 🌿 (b3.1.7)"),
("Leaves are broad, flat and thin to {{c1::maximise surface area}} for gas exchange and light capture; most are green because of {{c2::chlorophyll}}.",
 "The solar panels' shape. 🌿 (b3.1.7)"),
# --- B3.1.8 tissue distribution in a leaf ---
("Top to bottom in a leaf plan diagram: upper epidermis → {{c1::palisade mesophyll}} → {{c2::vascular bundle}} (vein) → {{c3::spongy mesophyll}} → {{c4::lower epidermis}} (with stomata).",
 "THE PLAN DIAGRAM ORDER — memorise. ✏️ (b3.1.8)"),
("A plan diagram shows the distribution of {{c1::tissues}} — outline shapes and their junctions — and NOT individual {{c2::cells}}.",
 "Big outlines only. ✏️ (b3.1.8)"),
("The palisade mesophyll sits on the {{c1::upper}} half of the leaf to maximise light absorption; the spongy mesophyll sits near the {{c2::stomata}} on the underside for gas exchange; the vascular bundle sits {{c3::centrally}} so all tissues are served.",
 "The seating plan. ✏️ (b3.1.8)"),
("Most stomata are on the {{c1::lower}} surface of the leaf, keeping the exchange channel open and less obstructed.",
 "Windows on the quiet street. ✏️ (b3.1.8)"),
("Sun leaves are thicker with a thicker {{c1::cuticle}} and more layers of {{c2::palisade}} mesophyll; shade leaves are thinner with less.",
 "The tan lines of botany. ☀️ (b3.1.8)"),
# --- B3.1.9 transpiration ---
("{{c1::Transpiration}} is the loss of water vapour from plants — a consequence of {{c2::gas exchange}} through the moist surface of the leaf.",
 "THE WATER BILL — the leak for the moist floor. 💦 (b3.1.9)"),
("Four abiotic factors affecting transpiration: temperature {{c1::↑ (positive correlation)}}, humidity {{c2::↓ (negative)}}, wind {{c3::↑}}, and light {{c4::↑}}.",
 "Hot·dry·windy·sunny = the biggest leak. 🌡 (b3.1.9)"),
("High temperature increases transpiration because more {{c1::energy}} is available to evaporate water and warm air can hold more {{c2::water vapour}} before saturating.",
 "Hotter = thirstier air. 🌡 (b3.1.9)"),
("High humidity DECREASES transpiration because the {{c1::water-vapour gradient}} between the leaf's air spaces and the outside air is smaller.",
 "Muggy day = no gradient = no leak. 💧 (b3.1.9)"),
("Wind INCREASES transpiration because it {{c1::removes the humid layer}} of air around the leaf, steepening the gradient.",
 "The fan dries the floor. 🌬 (b3.1.9)"),
("Light INCREASES transpiration because it stimulates {{c1::stomata to open}} (photosynthesis needs CO₂).",
 "Open windows, more leak. ☀️ (b3.1.9)"),
("Guard cells close stomata at {{c1::night}} (when photosynthesis stops) and when the plant is under {{c2::water stress}}.",
 "Windows shut after hours. 🌙 (b3.1.9)"),
("A {{c1::potometer}} measures the rate of {{c2::water uptake}} by a leafy shoot — a bubble in a capillary tube moves as water is taken up.",
 "The leak meter. 🧪 (b3.1.9)"),
# --- B3.1.10 stomatal density ---
("{{c1::Stomatal density}} = the number of stomata per unit area (per mm²): mean number of stomata ÷ {{c2::area of the field of view}}.",
 "COUNT THE WINDOWS. 🔬 (b3.1.10)"),
("Two techniques to observe stomata: an {{c1::epidermal peel}} (easy with Commelina / Tradescantia) and a {{c2::nail-varnish cast}} (for smooth, hairless leaves).",
 "Peel it or cast it. 🔬 (b3.1.10)"),
("NOS: the reliability of quantitative data is increased by {{c1::repeating}} measurements — replicate counts from multiple leaves and areas, then find the {{c2::mean}}.",
 "REPEAT. MEASUREMENTS. The official NOS statement. 🔬 (b3.1.10)"),
("Under water stress, dehydrated mesophyll cells release the hormone {{c1::abscisic acid (ABA)}}, which triggers {{c2::K⁺ efflux}} from guard cells → they lose {{c3::turgor}} and become {{c4::flaccid}} → the stoma closes.",
 "ABA = the manager's 'close the windows' call. 🚪 (b3.1.10)"),
("Stomatal density can vary due to {{c1::genetic}} factors or growth under different {{c2::environmental}} conditions.",
 "Nature and nurture, window edition. 🔬 (b3.1.10)"),
# --- B3.1.11 haemoglobin (AHL) ---
("Oxygen is barely soluble in water — less than {{c1::50 cm³ per dm³}} at 37°C — but blood carries over {{c2::200 cm³}} per dm³ thanks to haemoglobin in red blood cells.",
 "Why we need the courier. 🩸 (b3.1.11)"),
("Haemoglobin is a conjugated protein with {{c1::four polypeptide chains}}, each with an iron-containing {{c2::haem group}} that reversibly binds one {{c3::O₂}} molecule (so Hb carries up to 4 O₂).",
 "4 seats, 4 guests. 🪑 (b3.1.11)"),
("{{c1::Cooperative binding}}: as each O₂ binds it alters the conformation of haemoglobin, making subsequent binding {{c2::easier}} — so Hb is mostly empty ({{c3::T state}}) or full ({{c4::R state}}).",
 "The first guest unlocks the rest. 🪑 (b3.1.11)"),
("CO₂ binds haemoglobin at an {{c1::allosteric site}} (not the haem group) and causes a conformational change that {{c2::lowers}} haemoglobin's affinity for oxygen.",
 "CO₂ loosens the grip. 🩸 (b3.1.11)"),
("Adult haemoglobin has two {{c1::alpha}} and two {{c2::beta}} chains; foetal haemoglobin replaces the beta chains with {{c3::gamma}} chains, which have a {{c4::higher affinity}} for oxygen.",
 "HbA = α₂β₂, HbF = α₂γ₂. 👶 (b3.1.11)"),
("At the {{c1::placenta}}, foetal haemoglobin loads O₂ while adult haemoglobin unloads it — the handover that lets the foetus steal oxygen from the mother's blood.",
 "The VIP hatch handover. 👶 (b3.1.11)"),
("After birth, foetal haemoglobin is almost completely replaced by adult haemoglobin within about {{c1::6 months}}.",
 "The courier gets the new uniform. 👶 (b3.1.11)"),
# --- B3.1.12 Bohr shift (AHL) ---
("The {{c1::Bohr shift}}: increased {{c2::CO₂}} causes increased dissociation (unloading) of oxygen from haemoglobin, delivering more O₂ to {{c3::actively respiring tissues}}.",
 "RIGHT = RELEASE. 🔥 (b3.1.12)"),
("In red blood cells, CO₂ reacts: CO₂ + H₂O → {{c1::H⁺ + HCO₃⁻}}. The H⁺ lowers the {{c2::pH}} (7.4 in lungs → ~7.2 in active muscle), and lower pH reduces haemoglobin's {{c3::affinity for oxygen}}.",
 "The acid grip-loosener. 🧪 (b3.1.12)"),
("CO₂ also binds directly to the {{c1::amino terminal}} of haemoglobin's polypeptide chains, forming {{c2::carbaminohaemoglobin}}, which further lowers O₂ affinity.",
 "The second loosener. 🧪 (b3.1.12)"),
("Each haemoglobin can also transport up to {{c1::4 CO₂}} molecules back to the lungs for disposal.",
 "The courier hauls both ways. 🔄 (b3.1.12)"),
("The Bohr shift is beneficial because it releases oxygen {{c1::exactly where}} cell respiration is producing CO₂ — the hardest-working tissues get the most O₂.",
 "The hottest party gets the most air. 🔥 (b3.1.12)"),
# --- B3.1.13 oxygen dissociation curves (AHL) ---
("An oxygen dissociation curve plots haemoglobin {{c1::saturation (%)}} against the {{c2::partial pressure of oxygen}} (kPa) — it represents the {{c3::affinity}} of haemoglobin for oxygen at different O₂ concentrations.",
 "The courier's loading chart. 📈 (b3.1.13)"),
("The adult dissociation curve is {{c1::sigmoidal (S-shaped)}} because of {{c2::cooperative binding}}: loading gets easier as seats fill, so saturation swings up over a narrow pO₂ range.",
 "The S-shape IS cooperative binding. 📈 (b3.1.13)"),
("The three regions of the S-curve: at high pO₂ (lungs) the curve {{c1::plateaus}} (~100% saturated); in the steep middle (respiring tissues, ~5 kPa) small pO₂ changes cause {{c2::large}} changes in saturation; at very low pO₂ the curve is {{c3::flat}} again.",
 "Plateau top, steep middle, flat bottom. 📈 (b3.1.13)"),
("Foetal haemoglobin's curve is shifted to the {{c1::left}} of adult haemoglobin because it has a {{c2::higher affinity}} — so in the placenta it loads O₂ while maternal Hb unloads it.",
 "LEFT = LOCKED ON. 👶 (b3.1.13)"),
("A shift of the dissociation curve to the {{c1::right}} (as with increased CO₂ / Bohr shift) means lower affinity — more O₂ released at any given pO₂.",
 "RIGHT = RELEASE. 🔥 (b3.1.13)"),
("Above about {{c1::10 kPa}} of oxygen, haemoglobin is essentially 100% saturated — that's why alveolar pO₂ (10–13 kPa) fully loads the courier.",
 "Full tank at 10 kPa. 📈 (b3.1.13)"),
]

deck = genanki.Deck(DECK_ID, "Bio HL")
for text, extra in CARDS:
    deck.add_note(genanki.Note(model=model, fields=[text, extra]))

genanki.Package(deck).write_to_file(OUT)
print(f"Wrote {OUT}: {len(CARDS)} notes, {sum(1 for _ in model.templates)} template")
