#!/usr/bin/env python
# Deep body/SVG/quiz metaphor strip for bio study-hub pages.
# Context-aware, EXACT-STRING replacements (assert count==1 per replacement so
# a mismatch fails loudly instead of silently mis-mapping biology). Only whole
# phrases are changed; no biological facts are altered, only the club/metaphor
# framing is replaced with direct factual language.
import re, os, sys

BASE = r"C:/Users/ASUS/Desktop/Hermes_Workspace/study-hub/topics/bio"

# page -> list of (old_exact_substring, new_exact_substring)
# old must appear EXACTLY once in the file (asserted); if it can appear more
# than once, use a fuller/phrase-form old string.
STRIP = {
"muscle-motility": [
  ("THE SARCOMERE — ONE DANCE FLOOR", "THE SARCOMERE"),
  ("READ THE DANCE FLOOR:", "READ THE SARCOMERE:"),
  ("<b>Think club:</b> the myosin heads are dancers doing a conga — each one grabs the rail (actin), hauls themselves along, lets go, sprints to the next rail.",
   "<b>How it works:</b> the myosin heads are like ratchets — each one binds actin, pulls itself along, lets go, and re-attaches to the next actin site."),
  ("One DJ controls a whole section of the crowd", "One motor neuron controls all the muscle fibres of a motor unit"),
  ("ONE MOTOR UNIT — ONE DJ, MANY DANCERS", "ONE MOTOR UNIT — ONE MOTOR NEURON, MANY FIBRES"),
  ("Fibres of different units intermingle so the club floor fills evenly.",
   "Fibres of different motor units are intermingled so contraction is even across the muscle."),
  ("Synovial joints — the VIP doors", "Synovial joints — the freely movable joints"),
  ("the hip is the club's best example", "the hip is the best example"),
  ("Job at the club", "Role"),
  ("THE HIP — BALL-AND-SOCKET VIP DOOR", "THE HIP — BALL-AND-SOCKET JOINT"),
  ("External vs internal — same club, opposite doors", "External vs internal — opposite surfaces"),
  ("THE DOLPHIN — WATERPROOF VIP", "THE DOLPHIN — ADAPTED FOR SWIMMING"),
  ("Follow the club layout from entrance to VIP lounge.", "Follow the way a muscle is organised, from a whole muscle to its fibres."),
  ("The myosin heads are the dancers — they bind actin", "The myosin heads bind actin"),
  ("You can't have a nightclub where nobody moves — but there are two very different door policies.",
   "There are two very different ways organisms move."),
  ("One neuron, many muscle fibres, all dancing on the same beat.",
   "One neuron, many muscle fibres, all contracting together."),
],
"homeostasis": [
   ("Four dials the club never lets drift", "Four variables the body holds steady"),
   ("CLUB SETPOINT — THE FOUR DIALS", "SET POINTS — THE FOUR VARIABLES"),
   ("The four dials of the club.", "The four variables held at a set point."),
   ("Negative feedback = the bouncer who pushes the crowd back to the set point from above OR below.",
    "Negative feedback = a response that pushes a variable back to its set point from above or below."),
   ("THE BOUNCER — NEGATIVE FEEDBACK LOOP", "NEGATIVE FEEDBACK LOOP"),
   ("The bouncer's loop.", "The negative-feedback loop."),
   ("Blood glucose is a dance floor kept perfectly crowded: when it's too full, insulin clears people out; when it's too empty, glucagon lets more in.",
    "Blood glucose is held at a set point: when it is too high, insulin lowers it; when it is too low, glucagon raises it."),
   ("Insulin and glucagon — the antagonistic DJ pair", "Insulin and glucagon — an antagonistic pair"),
   ("the dance floor's target capacity", "the set point for blood glucose"),
   ("Two antagonistic hormones, one negative feedback loop — the DJ pair keeps the floor at capacity",
    "Two antagonistic hormones, one negative feedback loop — the pair holds glucose at the set point"),
   ("Diabetes = the club that can't clear the dance floor. Type 1: the DJ (insulin) never shows up. Type 2: the speakers (receptors) are blown.",
    "Diabetes = a failure to control blood glucose. Type 1: insulin is not produced. Type 2: the body's cells do not respond properly to insulin."),
   ("TYPE 1 · no DJ", "TYPE 1 · no insulin"),
   ("The kidneys are the club's two bouncers at the back door: they chuck out toxic waste (excretion) and hold the door policy on water (osmoregulation).",
    "The kidneys excrete toxic waste and hold a steady water balance (osmoregulation)."),
   ("THE KIDNEY CLUB — ONE NEPHRON", "THE NEPHRON"),
   ("One night at Club Setpoint: everything connects back to the dials.", "How the homeostatic roles connect."),
   ("3 · Club Setpoint", "3 · Homeostasis"),
   ("Antagonistic pair, liver is the stage.", "An antagonistic pair, with the liver as the target organ."),
  ("ADH is the bouncer at the door of the collecting duct: when you're dehydrated he opens more water channels; when you're topped up he lets water walk out.",
   "ADH acts on the collecting duct: when you are dehydrated it inserts more water channels so more water is reabsorbed; when you are well hydrated it withdraws channels so water passes out."),
],
"transport": [
  ("serve the dance floor: ultra-narrow, ultra-branching, and built so thin that every single guest (cell) can trade with the bloodstream face to face.",
   "actually carry out exchange: they are ultra-narrow, heavily branched, and built so thin that every single cell can exchange substances with the bloodstream directly."),
  ("THE VIP CORRIDORS — CAPILLARY NETWORK", "THE CAPILLARY NETWORK"),
  ("The VIP corridors: narrow (~10 µm)", "The capillaries: narrow (~10 µm)"),
  ("many narrow corridors serve more guests than one wide boulevard.", "many narrow vessels exchange more efficiently than one wide vessel."),
  ("arteries and veins are just the transport corridors between the heart and the dance floor.",
   "arteries and veins are just the transport vessels between the heart and the exchange surfaces."),
  ("and the club's tempo is yours.", "and the circulation makes sense."),
  ("Blood leaving the heart has the DJ's pressure behind it.", "Blood leaving the heart is under pressure from the heart's contraction."),
  ("When the corridors behind the DJ booth clog up, the music stops.", "When the coronary arteries supplying the heart become blocked, the heart muscle is damaged."),
  ("<h3>When the DJ's power line kinks</h3>", "<h3>When the heart's own blood supply is blocked</h3>"),
  ("THE BLOCKED BACKSTAGE — CORONARY OCCLUSION", "CORONARY OCCLUSION"),
  ("The blocked backstage: coronary arteries", "The blocked coronary arteries"),
  ("Every club has a floor plan.", "Plant transport follows a route plan."),
  ("The heart is the DJ, and the beat sequence is the setlist: atria squeeze, ventricles slam, valves click shut — twice per second, every second. This is the club's unidirectional music system.",
   "The heart pumps blood, and the beat sequence is the cardiac cycle: atria contract, ventricles contract, valves close — twice per second, every second. This is the heart's unidirectional flow system."),
  ("Cardiac muscle</span> is the DJ's special gear: cells are <span class=\"cyan\">branched and connected",
   "Cardiac muscle</span> is specialised: cells are <span class=\"cyan\">branched and connected"),
  ("THE DJ'S DECK — HEART FRONTAL PLANE", "THE HEART — FRONTAL PLANE"),
  ("The DJ's deck: a frontal-plane heart showing unidirectional flow", "The heart (frontal plane): unidirectional flow"),
  ("Single vs double circulation: fish rave vs mammal club", "Single vs double circulation: fish vs mammals"),
  ("THE VIP ESCALATOR — PHLOEM TRANSLOCATION", "PHLOEM TRANSLOCATION"),
  ("The VIP escalator: sieve tubes", "The phloem: sieve tubes"),
  ("One night at Club Delivery: everything that moves — blood, water and sugar — connects through the same corridors.",
   "Everything that moves — blood, water and sugar — is carried through the same body."),
  ("B3.2 · Club Delivery", "B3.2"),
  ("VIP CORRIDORS<small>capillaries ~10 µm", "CAPILLARIES<small>capillaries ~10 µm"),
  ("BLOCKED BACKSTAGE<small>coronary atheroma", "CORONARY ATHEROMA<small>coronary atheroma"),
  ("THE DJ'S DECK<small>SA node", "THE HEART<small>SA node"),
  ("VIP ESCALATOR<small>phloem sieve tubes", "PHLOEM<small>phloem sieve tubes"),
  ("🪩 Capillaries = VIP corridors", "Capillaries = exchange vessels"),
],
"gas-exchange": [
  ("All organisms exchange gases — it's how the party (metabolism) keeps running:",
   "All organisms exchange gases — it is how metabolism keeps running:"),
  ("CO₂ is the waste smoke and must be removed, or the venue fills up and the crowd dies.",
   "CO₂ is a waste product and must be removed, or it builds up and the cells die."),
  ("SMALL CLUB (flatworm, amoeba)", "SIMPLE BODY (flatworm, amoeba)"),
  ("Every venue has the same four rules posted by the door. Break one and the club suffocates.",
   "Every exchange surface must follow the same four rules. Break one and gas exchange fails."),
  ("the dance floor has to fit the whole crowd", "the surface area has to be large enough for the whole body"),
  ("one-cell-deep velvet rope", "one cell thick"),
  ("No bouncer checks IDs — both gases are on the guest list.", "Both gases pass freely across the surface."),
  ("If the inside ever matches the outside, the party stops. The club must keep the inside O₂-poor and CO₂-rich — forever.",
   "If the inside ever matched the outside, exchange would stop. The body must keep the inside O₂-poor and CO₂-rich — continuously."),
  ("So the club runs three systems to keep the air fresh:", "So the body runs three systems to keep the air fresh:"),
  ("The route from the street to the VIP booths is a masterpiece of branching design.",
   "The route from the airways to the alveoli is a masterpiece of branching design."),
  ("lets the venue narrow or widen the corridors", "lets the lungs narrow or widen the airways"),
  ("THE VIP BOOTHS (ALVEOLI)", "THE ALVEOLI"),
  ("are the flattened, ultra-thin booth walls that do the exchanging.", "are the flattened, ultra-thin walls that carry out the exchange."),
  ("wrap each booth; blood", "wrap each alveolus; blood"),
  ("THE CLUB O₂ CUTAWAY:", "THE ALVEOLUS — CUTAWAY:"),
  ("one air-sac booth, drawn to order.", "one air sac, drawn to scale."),
  ("CO₂ (violet) diffuses out into the booth.", "CO₂ (violet) diffuses out into the alveolus."),
  ("the venue can constrict or relax its corridors.", "the lungs can constrict or relax the airways."),
  ("How much air can the venue hold?", "How much air can the lungs hold?"),
  ("The plant venue is solar-powered: it takes in CO₂, blows out O₂, and brews its own sugar",
   "The leaf is solar-powered: it takes in CO₂, releases O₂, and makes its own sugar"),
  ("THE VENUE'S BLUEPRINT (B3.1.7)", "THE LEAF — BLUEPRINT (B3.1.7)"),
  ("Keeps the club from leaking.", "Keeps the leaf from losing water."),
  ("the bouncer windows (usually on the lower epidermis)", "the pores that open and close (usually on the lower epidermis)"),
  ("haemoglobin, the club's private courier with four seats.", "haemoglobin, each molecule carrying up to four oxygen molecules."),
  ("it's what makes blood a 200+ cm³ club vs water's pathetic 50.", "it is what lets blood carry 200+ cm³ of oxygen versus only about 50 in water."),
  ("the first guest unlocks the rest", "the first oxygen molecule loosens the others"),
  ("the handover at the VIP hatch.", "the handover at the placenta."),
  ("CO₂ loosens the grip — exactly where the party is hardest", "CO₂ loosens the grip — exactly where respiration is fastest"),
  ("Club O₂ · the universal deal", "Gas exchange · the universal principle"),
  ("Diffusion flows downhill, and the club keeps the inside low-O₂ (blood flow) and the air fresh (ventilation).",
   "Diffusion flows down the gradient, and the body keeps the inside low-O₂ (blood flow) and the air fresh (ventilation)."),
],
"integration": [
  ("<h3>One club, many rooms, one conductor</h3>", "<h3>One body, many systems, one coordinating centre</h3>"),
  ("kidney failure kills the whole club, not just the kidney.", "kidney failure can kill the whole organism, not just the kidney."),
  ("THE CONDUCTOR — HIERARCHY OF SUBSYSTEMS", "HIERARCHY OF SUBSYSTEMS"),
  ("the whole club — cheetah sprinting", "the whole body — a cheetah sprinting"),
  ("FRAGILE CLUB", "FRAGILE ORGANISM"),
  ("and a single broken component can bring the whole club down.", "and a single broken component can bring the whole system down."),
  ("The conductor talks to the club through three channels: nerves (wired mics), hormones (radio signals) and blood (roadies hauling gear).",
   "The body communicates through three channels: nerves (fast electrical signals), hormones (chemical signals in the blood) and blood (transport)."),
  ("Every system in the club is wired into all three channels at once.", "Every system in the body is connected to all three channels at once."),
  ("THE THREE CHANNELS — HOW THE CONDUCTOR TALKS", "THE THREE CHANNELS — HOW THE BODY COMMUNICATES"),
  (">THE CONDUCTOR</text>", ">THE BRAIN / CNS</text>"),
  ("brain · DJ + manager", "brain · co-ordinator"),
  ("the DJ deciding which track to play next, based on what the crowd (receptors) is telling him.",
   "the brain deciding which response to make, based on what the receptors are reporting."),
  ("THE DJ BOOTH — BRAIN AS INTEGRATION CENTRE", "THE BRAIN AS INTEGRATION CENTRE"),
  ("FIG 3 — The DJ booth: information flows in", "FIG 3 — The brain: information flows in"),
  ("so the DJ booth upstairs doesn't have to think about everything.", "so the brain does not have to think about everything."),
  ("Sensory neurons carry input from receptors into the CNS (the mics picking up the crowd);",
   "Sensory neurons carry input from receptors into the CNS;"),
  ("the club's cable looms.", "the cable bundles."),
  ("The pain reflex is the fastest ride in the club: three neurons, one synapse short-cut in the spinal cord,",
   "The pain reflex is the fastest pathway: three neurons and one synapse in the spinal cord,"),
  ("The cerebellum is the floor manager at the back of the venue: it doesn't decide which muscles work, but it coordinates their timing",
   "The cerebellum coordinates the timing of muscles: it does not decide which muscles work, but it coordinates their timing"),
  ("Adrenaline (epinephrine) is the club's emergency broadcast: one radio signal from the adrenal glands and the whole venue switches to fight-or-flight mode.",
   "Adrenaline (epinephrine) is the emergency signal: one chemical released by the adrenal glands switches the whole body into fight-or-flight mode."),
  ("One signal, whole-club response.", "One signal, whole-body response."),
  ("Plants have their own conductor's desk: phytohormones like auxin, gibberellin and ethylene coordinate growth, bending toward light and ripening fruit — with positive feedback for the finale.",
   "Plants use phytohormones such as auxin, gibberellin and ethylene to coordinate growth, bending toward light and ripening fruit — with positive feedback reinforcing the response."),
  ("One night at the Conductor's Desk: every room plugs into the same three channels.", "All body systems plug into the same three channels."),
  ("THE CONDUCTOR'S DESK<small>C3.1", "INTEGRATION OF BODY SYSTEMS<small>C3.1"),
  ("BRAIN = DJ BOOTH", "BRAIN"),
  ("one broken group of cells can kill the whole club.", "one broken group of cells can kill the whole organism."),
  ("Wired mics, radio signals and roadies", "Nerves, hormones and blood"),
],
"photosynthesis": [
  ("<h3>The nightclub kitchen that feeds the whole planet</h3>", "<h3>Photosynthesis feeds the whole planet</h3>"),
  ("every calorie you've ever eaten was originally cooked in a solar kitchen.", "every calorie you've ever eaten was originally produced by photosynthesis."),
  ("chloroplast as a solar kitchen: sunlight hits solar-panel photosystems", "chloroplast: sunlight hits the photosystems"),
  ("THE SOLAR KITCHEN — LIGHT IN, GLUCOSE OUT", "PHOTOSYNTHESIS — LIGHT IN, GLUCOSE OUT"),
  ("CHLOROPLAST = THE KITCHEN", "THE CHLOROPLAST"),
  ("Every carbon atom in every living thing was fixed in a kitchen like this one", "Every carbon atom in every living thing was fixed by photosynthesis"),
  ("FIG 1</b> — The solar kitchen.", "FIG 1</b> — Photosynthesis: light energy into chemical energy."),
  ("You are looking at the planet's only kitchen.", "You are looking at the process that feeds the planet."),
  ("<h3>Every kitchen needs its spice rack</h3>", "<h3>Accessory pigments</h3>"),
  ("widening the kitchen's menu of usable light.", "widening the range of usable light."),
  ("it sends the green back to the kitchen.", "it reflects the green light."),
  ("AKA: the bottlenecks — turn one tap and the kitchen speeds up, but only until the next tap runs dry.",
   "AKA: the limiting factors — raise one and the rate rises, but only until the next factor becomes limiting."),
  ("<h3>Pumping the kitchen full of CO₂</h3>", "<h3>Raising the CO₂ concentration</h3>"),
  ("AKA: the CO₂ bubbler — the club's bouncer sprays extra carbon dioxide into the air and watches the kitchen cook faster.",
   "AKA: enriching the air with extra carbon dioxide and watching the rate rise."),
  ("when the other factors can't hold the kitchen back.", "when the other factors are not limiting."),
  ("why a crowd of pigments beats a single chlorophyll molecule.", "why many pigment molecules together capture more light than a single chlorophyll molecule."),
  ("<h3>One pigment is useless; an array is a power plant</h3>", "<h3>One pigment is not enough; an array captures far more</h3>"),
  ("AKA: the solar panels on the kitchen roof — thousands of little collector tiles funneling light into one powerful socket.",
   "AKA: the photosystems — hundreds of pigment molecules funnelling light energy into one reaction centre."),
  ("so even dim light keeps the kitchen running.", "so even dim light keeps photosynthesis running."),
  ("AKA: the water splitter — the kitchen's tap that doubles as a power supply, gushing oxygen as a side effect.",
   "AKA: the splitting of water — providing electrons and releasing oxygen as a by-product."),
  ("<b>Think of it as zoning laws:</b> the kitchen keeps the hobs (PSII) in one wing and the dishwashers (ATP synthase) in another",
   "<b>Think of it as compartmentalisation:</b> PSII and ATP synthase are in the thylakoid membrane, but all connected to the same proton gradient (the lumen)."),
  ("<h3>Rubisco, the head chef, and his three-station line</h3>", "<h3>Rubisco and the Calvin cycle</h3>"),
  ("Its head chef is <span class=\"accent\">Rubisco</span>", "Its key enzyme is <span class=\"accent\">Rubisco</span>"),
  ("THE ASSEMBLY LINE — CALVIN CYCLE (IN THE STROMA)", "THE CALVIN CYCLE (IN THE STROMA)"),
  ("RUBISCO — THE HEAD CHEF", "RUBISCO"),
  ("FIG 12</b> — The Calvin cycle assembly line.", "FIG 12</b> — The Calvin cycle."),
  ("What the kitchen actually serves — and why cutting light or CO₂ shuts the whole club down.",
   "What photosynthesis actually produces — and why cutting light or CO₂ shuts the whole process down."),
  ("Two halves, one kitchen: the light-dependent reactions charge the batteries the Calvin cycle spends — cut either supply and the whole club goes dark",
   "Two halves, one process: the light-dependent reactions make the ATP and reduced NADP the Calvin cycle uses — cut either supply and the whole process stops"),
  ("No light → no batteries → assembly line stalls.", "No light → no ATP/NADPH → the Calvin cycle stops."),
  ("One night at the Solar Kitchen: light in, glucose out, everything connected.", "Light in, glucose out: the two halves connect."),
  ("THE SOLAR KITCHEN<small>C1.", "PHOTOSYNTHESIS<small>C1."),
  ("ASSEMBLY LINE<small>C1.", "CALVIN CYCLE<small>C1."),
  ("Calvin cycle (stroma, Rubisco the head chef", "Calvin cycle (stroma, Rubisco"),
],
"respiration": [
  ("ATP is the club's currency — the token that distributes energy everywhere it's needed.",
   "ATP is the energy currency — the molecule that carries energy to wherever it is needed."),
  ("One token fits every machine in the club", "The same ATP molecule powers every process"),
  ("The club only runs if the tokens get spent.", "Respiration keeps energy available only if ATP is continually regenerated."),
  ("Continual regeneration of ATP from ADP + Pi is what keeps the party alive.",
   "Continual regeneration of ATP from ADP + Pi is what keeps a supply of energy available."),
  ("Cell respiration is the club's power grid: it oxidises carbon compounds and uses the released energy to produce ATP.",
   "Cell respiration is the cell's energy system: it oxidises carbon compounds and uses the released energy to produce ATP."),
  ("3 · DANCE FLOOR", "3 · GLYCOLYSIS"),
  ("Aerobic respiration is the main stage — huge yield, needs oxygen, uses mitochondria.",
   "Aerobic respiration is the main pathway — high yield, needs oxygen, uses mitochondria."),
  ("Two sets of word equations, one club", "Two sets of word equations, one process"),
  ("MAIN STAGE VS BACKUP — AEROBIC VS ANAEROBIC", "AEROBIC VS ANAEROBIC"),
  ("MAIN STAGE · AEROBIC", "AEROBIC"),
  ("OXYGEN DEBT = the bill after the party", "OXYGEN DEBT = the extra oxygen required after exercise"),
  ("How fast is the club burning fuel?", "How fast is the cell respiring?"),
  ("NAD is the valet that carries the hydrogen (and its electrons) away.",
   "NAD is the carrier that takes up the hydrogen (and its electrons)."),
  ("Redox: one club loses electrons, another gains them", "Redox: one molecule loses electrons, another gains them"),
  ("the investment: 2 ATP per glucose · repaid with interest in stage 4", "the investment: 2 ATP per glucose · repaid four-fold in stage 4"),
  ("Remember: the 2 ATP spent in stage 1 are an investment — they're repaid 4-fold in stage 4.",
   "Remember: the 2 ATP used in stage 1 are repaid four-fold in stage 4."),
  ("Stage 3 · Oxidation — hand the hydrogen to the valet", "Stage 3 · Oxidation — hydrogen is removed and carried by NAD"),
  ("Pyruvate takes the hydrogen so the party can continue", "Pyruvate accepts the hydrogen so NAD is regenerated"),
  ("so the 2-ATP-per-glucose party continues as long as glucose holds out", "so the 2-ATP-per-glucose pathway continues as long as glucose holds out"),
  ("THE BACKSTAGE BREWERY — YEAST ETHANOL FERMENTATION", "YEAST — ETHANOL FERMENTATION"),
  ("FIG 12 — Backstage brewery: decarboxylation", "FIG 12 — Yeast fermentation: decarboxylation"),
  ("Oxygen is the final customer at the end of the conveyor belt: it has the strongest affinity for electrons of anyone in the club, so it takes the spent electrons — plus protons from the matrix — and leaves water.",
   "Oxygen is the final electron acceptor at the end of the electron transport chain: it has the strongest affinity for electrons, so it accepts the spent electrons — plus protons from the matrix — and forms water."),
  ("THE POWER PLANT<small>C1.2 · Cell Respiration", "CELL RESPIRATION<small>C1.2"),
  ("MAIN STAGE VS BACKUP<small>C1.2.5", "AEROBIC VS ANAEROBIC<small>C1.2.5"),
  ("BACKSTAGE BREWERY<small>C1.2.10", "YEAST FERMENTATION<small>C1.2.10"),
  ("WATER-WHEEL<small>C1.2.15", "CHEMIOSMOSIS<small>C1.2.15"),
  ("DELIVERY DOCK<small>C1.2.11", "LINK REACTION<small>C1.2.11"),
  ("THE CONVEYOR BELT — ETC + PROTON GRADIENT", "THE ELECTRON TRANSPORT CHAIN"),
  ("END OF THE CONVEYOR BELT", "END OF THE ELECTRON TRANSPORT CHAIN"),
  ("THE WATER-WHEEL — CHEMIOSMOSIS + ATP SYNTHASE", "CHEMIOSMOSIS & ATP SYNTHASE"),
  ("THE DELIVERY DOCK — THE LINK REACTION (MATRIX)", "THE LINK REACTION (MATRIX)"),
  ("TOKENS AT WORK — THREE WAYS ATP GETS SPENT", "ATP AT WORK — THREE WAYS ATP IS USED"),
  ("<h2>THE DELIVERY DOCK — ACETYL COA</h2>", "<h2>THE LINK REACTION — ACETYL COA</h2>"),
  ("The respirometer is the club's fuel gauge: a sealed chamber", "The respirometer is a sealed chamber"),
  ("FIG 15</b> — The conveyor belt: carriers accept electron pairs", "FIG 15</b> — The electron transport chain: carriers accept electron pairs"),
  ("The first stage is glycolysis", "The first stage is glycolysis"),
],
"reproduction": [
  ("THE LOOP VS THE REMIX — SEXUAL VS ASEXUAL", "SEXUAL VS ASEXUAL REPRODUCTION"),
  ("REMIX · SEXUAL", "SEXUAL"),
  ("Sexual = the REMIX deck: meiosis halves 2n → n gametes, fusion doubles n → 2n zygote, variation every generation.",
   "Sexual = meiosis halves 2n → n gametes, fusion doubles n → 2n zygote, variation every generation."),
  ("♂ VIP COURIER — MALE GAMETE", "♂ MALE GAMETE"),
  ("♀ VIP LOUNGE — FEMALE GAMETE", "♀ FEMALE GAMETE"),
  ("<h3>Backstage tour: who makes, stores and delivers the tickets</h3>", "<h3>Who makes, stores and delivers the gametes</h3>"),
  ("THE MALE BACKSTAGE — MALE REPRODUCTIVE SYSTEM", "THE MALE REPRODUCTIVE SYSTEM"),
  ("FIG 3 — Male backstage chain:", "FIG 3 — Male reproductive system:"),
  ("The female reproductive system runs the whole venue: the ovary releases the egg, the oviduct hosts fertilization, the uterus hosts the pregnancy, and the cervix, vagina and vulva guard the entrances.",
   "The female reproductive system: the ovary releases the egg, the oviduct hosts fertilization, the uterus hosts the pregnancy, and the cervix, vagina and vulva guard the entrances."),
  ("THE FEMALE BACKSTAGE — FEMALE REPRODUCTIVE SYSTEM", "THE FEMALE REPRODUCTIVE SYSTEM"),
  ("FIG 4 — Female backstage:", "FIG 4 — Female reproductive system:"),
  ("The menstrual cycle is the venue's monthly calendar (~28 days):", "The menstrual cycle is a monthly cycle (~28 days):"),
  ("<h3>One guest, one door, one fusion</h3>", "<h3>One sperm, one egg, one fusion</h3>"),
  ("THE LAB REMIX — IVF STEP BY STEP", "IVF STEP BY STEP"),
  ("IVF = the lab remix: doctors control timing the natural cycle hides", "IVF: doctors control the timing that the natural cycle hides"),
  ("<h3>Structure of the venue, and how insects work the room</h3>", "<h3>Structure of the flower, and how insects pollinate</h3>"),
  ("THE OPEN-AIR VENUE — INSECT-POLLINATED FLOWER", "INSECT-POLLINATED FLOWER"),
  ("FIG 8 — The open-air venue:", "FIG 8 — The insect-pollinated flower:"),
  ("<h3>The DJ booth, the tower, and the remix of the body</h3>", "<h3>The flower, the pollen tube and fertilisation</h3>"),
  ("Polyspermy is the club's worst nightmare — two sperm in one egg makes a triploid zygote that dies.",
   "Polyspermy is harmful — two sperm in one egg makes a triploid zygote that dies."),
  ("<h3>One guest per egg, enforced by two reactions</h3>", "<h3>One sperm per egg, enforced by two reactions</h3>"),
  ("THE VELVET ROPE — PREVENTING POLYSPERMY (AHL)", "PREVENTING POLYSPERMY (AHL)"),
  ("only ONE guest gets in — polyspermy → triploid zygote → non-viable, dies", "only ONE sperm gets in — polyspermy → triploid zygote → non-viable, dies"),
  ("FIG 13 — The velvet rope:", "FIG 13 — Preventing polyspermy:"),
  ("Childbirth is the crowd chanting for an encore: oxytocin drives contractions, stretch receptors demand more oxytocin, contractions get stronger — a rare positive feedback loop that ends the residency.",
   "Childbirth is a positive feedback loop: oxytocin drives contractions, stretch receptors demand more oxytocin, contractions get stronger — a rare positive feedback loop that ends the pregnancy."),
  ("The positive-feedback encore", "The positive feedback loop"),
  ("the encore chant —", "the feedback loop —"),
  ("foetal hormones turn it off so the encore can start.", "foetal hormones turn it off so contractions can begin."),
  ("That variety is the club's insurance policy when the environment changes.", "That variety is the species' insurance when the environment changes."),
  ("THE ENCORE<small>D3.", "REPRODUCTION<small>D3."),
  ("LOOP VS REMIX<small>D3.", "SEXUAL VS ASEXUAL<small>D3."),
  ("BACKSTAGE TOURS<small>D3.", "REPRODUCTIVE SYSTEMS<small>D3."),
  ("LAB REMIX<small>D3.", "IVF<small>D3."),
  ("OPEN-AIR VENUE<small>D3.", "FLOWER POLLINATION<small>D3."),
  ("VELVET ROPE AHL", "PREVENTING POLYSPERMY AHL"),
  ("🎧 Sexual = remix, asexual = loop", "Sexual = variation, asexual = clones"),
  ("🧪 IVF = lab remix", "IVF = lab fertilisation"),
  ("🌸 Flower = open-air venue", "Flower = insect pollination"),
  ("🔒 One guest per egg", "One sperm per egg"),
  ("👶 Childbirth = positive-feedback encore", "Childbirth = positive feedback"),
  ("✅ Sexual = remix (two parents, meiosis + fusion, genetically different offspring).",
   "✅ Sexual = two parents, meiosis + fusion, genetically different offspring."),
  ("The venue's rooms, from stage to front door", "The reproductive organs, from ovary to vagina"),
  ("seeds leave the club", "seeds are dispersed"),
],
}

def apply(page):
    f = os.path.join(BASE, page, "index.html")
    s = open(f, encoding="utf-8", errors="replace").read()
    n = 0
    for old, new in STRIP[page]:
        c = s.count(old)
        if c == 0:
            continue            # already applied (idempotent)
        assert c == 1, f"{page}: '{old[:40]}...' occurs {c}x (expected 1)"
        s = s.replace(old, new); n += 1
    open(f, "w", encoding="utf-8", errors="replace").write(s)
    return n

for page in STRIP:
    print("OK", page, "replacements:", apply(page))
